version: '1.5'
services:
  db:
    image: mysql
    container_name: database-local
    environment:
      MYSQL_ROOT_PASSWORD: prvzcpy
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    # restart: always

  api:
    build: "./api"
    container_name: python-container
    volumes:
      - /api:/home/python/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  loki:
    image: grafana/loki:2.7.5
    ports:
      - 3100:3100
    command:
    - -config.file="/etc/config/loki-config.yaml"
    - -print-config-stderr=true
    networks:
      - loki
    volumes:
      - ./api/config/loki-config.yaml:/etc/config/loki-config.yaml
  
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /api/log:/var/log
      - ./api/config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file="/etc/promtail/promtail-config.yaml"
    networks:
      - loki
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3200:3200"
    networks:
      - loki

networks:
  loki: