version: '2.5'
services:
  db:
    image: mysql
    container_name: database-local
    environment:
      MYSQL_ROOT_PASSWORD: prvzcpy
      MYSQL_INIT_DB: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - /var/lib/mysql
      - ./api/db/CriarDatabase.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  api:
    build: "./api"
    container_name: python-container
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  loki:
    build: ./etc/loki
    ports:
      - 3100:3100
    command:
    - -config.file="/etc/loki/loki-config.yaml"
    - -print-config-stderr=true
    networks:
      - loki
  
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /aplicacao.log:/var/log
      - ./etc/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file="/etc/promtail/promtail-config.yaml"
    networks:
      - loki
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3200:3200"
    networks:
      - loki

networks:
  loki: