version: '3'
services:
  db:
    image: mysql
    container_name: database-local
    environment:
      MYSQL_ROOT_PASSWORD: prvzcpy
      MYSQL_INIT_DB: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - /var/lib/mysql
      - ./api/db/CriarDatabase.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.21.0.2

  api:
    build: "/api"
    container_name: python-container
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: db:3306
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.21.0.3
  
  loki:
    build: /etc/loki
    ports:
      - 3100:3100
    command:
    - -config.file="/etc/loki/loki-config.yaml"
    - -print-config-stderr=true
    networks:
      - loki
  
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /aplicacao.log:/var/log
      - ./etc/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file="/etc/promtail/promtail-config.yaml"
    networks:
      - loki
  
  grafana:
    build: etc/grafana
    ports:
      - "3200:3200"
    networks:
      app_net:
        ipv4_address: 172.21.0.4

networks:
  loki:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16