kind: ConfigMap
metadata:
  name: grafana-agent-traces
apiVersion: v1
data:
  # - job_name: 'flaskapi_gerenciador'
  # static_configs:
  #   - targets: ['flask-service.flaskapi.svc.cluster.local:5000']
  agent.yaml: |
    traces:
        configs:
          - batch:
                send_batch_size: 1000
                timeout: 5s
            name: default
            receivers:
                jaeger:
                    protocols:
                        grpc:
                          endpoint: "0.0.0.0:14250"
                        thrift_binary:
                          "endpoint: 0.0.0.0:6832"
                        thrift_compact:
                          "endpoint: 0.0.0.0:6831"
                        thrift_http:
                          "endpoint: 0.0.0.0:14268"    
                otlp:
                    protocols:
                        grpc:
                          endpoint: "0.0.0.0:4317"
                        http:
                          endpoint: "0.0.0.0:4318"
                zipkin:
                  endpoint: "0.0.0.0:9411"
            remote_write:
              - endpoint: http://grafana-tempo-hml-api.dock.tech
                protocol: "http"
                insecure: true