version: '1.0'
services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: prvzcpy
    volumes:
      - ./Instrumentacao\ Python/db/data:/var/lib/mysql
    restart: always

  api:
    image: python
    build: "./Instrumentacao\ Python"
    container_name: python-container
  
  loki:
    image: grafana/loki:2.7.5
    ports:
      - 3100:3100
    command:
    - -config.file=/etc/loki/local-config.yaml
    - -print-config-stderr=true
    networks:
      - loki