traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      jaeger:
        protocols:
          grpc:
            endpoint: "0.0.0.0:14250"
          thrift_binary:
            "endpoint: "0.0.0.0:6832"
          thrift_compact:
            "endpoint: 0.0.0.0:6831"
          thrift_http:
            "endpoint: 0.0.0.0:14268"
      zipkin:
        endpoint: "0.0.0.0:9411"    
    remote_write:
      - endpoint: http://grafana-tempo-hml-api.dock.tech
        insecure: true
        protocol: "http"
    batch:
      timeout: 5s
      send_batch_size: 100