traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"  
    remote_write:
      - endpoint: http://grafana-tempo-hml-api.dock.tech
        insecure: true
        protocol: "http"
    batch:
      timeout: 5s
      send_batch_size: 100